import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai';
import Image from 'next/image';
import profilePic from '../../public/Profilepic.png';
import cloud from '../../public/cloud.jpg';
import code from '../../public/code.jpg';
import consulting from '../../public/consulting.jpg';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl'>developer</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill className='cursor-pointer mx-6'/></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-400 text-white px-4 py-2 rounded' href="#">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl text-teal-700 font-medium'>Sagar Bakshi</h2>
            <h3 className='text-2xl mt-3 font-semibold'>Cloud Architect and Developer</h3>
            <p className='text-md py-5 leading-6 text-gray-800'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias, accusamus? Cum illum at perspiciatis, alias error, distinctio sit nemo natus quibusdam, molestias ratione eius sed voluptate iure. Ullam, harum laudantium!</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 pb-10 text-cyan-900 cursor-pointer'>
            <AiFillTwitterCircle/>
            <AiFillLinkedin/>
            <AiFillYoutube/>
          </div>
          <div className='relative bg-gradient-to-b from-teal-500 to-teal-200 mx-auto mt-20 w-60 h-60 overflow-hidden'>
            <Image src={profilePic} fill="true"/>
          </div>
        </section>

        {/* Section Services */}

        <section>
          <div>
            <h3 className='text-4xl text-cyan-900 mb-3 mt-4'>Services I offer</h3>
            <p className='text-md py-5 leading-6 text-gray-800'>Lorem ipsum, dolor sit amet consectetur adipisicing <span className='text-cyan-500'>Agency</span> Magnam id esse quos modi <span className='text-cyan-500'>Startups</span> est magni ex qui recusandae veritatis? Voluptas similique eligendi corrupti doloremque numquam, explicabo illum quisquam harum ducimus.</p>
            <p className='text-md py-5 leading-6 text-gray-800'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos perferendis officia suscipit delectus similique consectetur, esse debitis, magnam ipsum nobis repudiandae hic incidunt fuga. Omnis modi sed autem eveniet nesciunt!</p>
          </div>
          <div>
            <div>
              <Image src={cloud} width={100} height={100}/>
              <h3 className='text-3xl'>Cloud Architecting</h3>
              <p className='text-gray-900'>I am certified cloud architect. worked on many projects.</p>
              <h4>Tools I use</h4>
              <p className='text-gray-900'>AWS</p>
              <p className='text-gray-900'>Azure</p>
              <p className='text-gray-900'>Security</p>
            </div>
            <div>
            <Image src={consulting} width={100} height={100} />
            <h3></h3>
            </div>
            <div>
            <Image src={code} width={100} height={100}/>
            <h3></h3>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
